import type { CountryPool } from "./types.js";

export type Continent = Exclude<CountryPool, "world">;

export interface CountryQuestion {
  id: string;
  name: string;
  continent: Continent;
  mapId?: string;
  fallbackPoint?: [number, number];
  aliases?: string[];
}

export const COUNTRY_POOL_LABELS: Record<CountryPool, string> = {
  world: "Whole World",
  europe: "Europe",
  asia: "Asia",
  africa: "Africa",
  northAmerica: "North America",
  southAmerica: "South America",
  oceania: "Oceania"
};

export const COUNTRIES: CountryQuestion[] = [
  { id: "ALB", name: "Albania", continent: "europe", mapId: "008" },
  { id: "AND", name: "Andorra", continent: "europe", mapId: "020", fallbackPoint: [1.52, 42.51] },
  { id: "AUT", name: "Austria", continent: "europe", mapId: "040" },
  { id: "BLR", name: "Belarus", continent: "europe", mapId: "112" },
  { id: "BEL", name: "Belgium", continent: "europe", mapId: "056" },
  { id: "BIH", name: "Bosnia and Herzegovina", continent: "europe", mapId: "070", aliases: ["Bosnia"] },
  { id: "BGR", name: "Bulgaria", continent: "europe", mapId: "100" },
  { id: "HRV", name: "Croatia", continent: "europe", mapId: "191" },
  { id: "CZE", name: "Czech Republic", continent: "europe", mapId: "203", aliases: ["Czechia"] },
  { id: "DNK", name: "Denmark", continent: "europe", mapId: "208" },
  { id: "EST", name: "Estonia", continent: "europe", mapId: "233" },
  { id: "FIN", name: "Finland", continent: "europe", mapId: "246" },
  { id: "FRA", name: "France", continent: "europe", mapId: "250" },
  { id: "DEU", name: "Germany", continent: "europe", mapId: "276" },
  { id: "GRC", name: "Greece", continent: "europe", mapId: "300" },
  { id: "HUN", name: "Hungary", continent: "europe", mapId: "348" },
  { id: "ISL", name: "Iceland", continent: "europe", mapId: "352" },
  { id: "IRL", name: "Ireland", continent: "europe", mapId: "372" },
  { id: "ITA", name: "Italy", continent: "europe", mapId: "380" },
  { id: "XKX", name: "Kosovo", continent: "europe", fallbackPoint: [20.9, 42.6] },
  { id: "LVA", name: "Latvia", continent: "europe", mapId: "428" },
  { id: "LIE", name: "Liechtenstein", continent: "europe", mapId: "438", fallbackPoint: [9.55, 47.16] },
  { id: "LTU", name: "Lithuania", continent: "europe", mapId: "440" },
  { id: "LUX", name: "Luxembourg", continent: "europe", mapId: "442" },
  { id: "MLT", name: "Malta", continent: "europe", mapId: "470", fallbackPoint: [14.38, 35.94] },
  { id: "MDA", name: "Moldova", continent: "europe", mapId: "498", aliases: ["Republic of Moldova"] },
  { id: "MCO", name: "Monaco", continent: "europe", mapId: "492", fallbackPoint: [7.42, 43.73] },
  { id: "MNE", name: "Montenegro", continent: "europe", mapId: "499" },
  { id: "NLD", name: "Netherlands", continent: "europe", mapId: "528", aliases: ["Holland"] },
  { id: "MKD", name: "North Macedonia", continent: "europe", mapId: "807", aliases: ["Macedonia"] },
  { id: "NOR", name: "Norway", continent: "europe", mapId: "578" },
  { id: "POL", name: "Poland", continent: "europe", mapId: "616" },
  { id: "PRT", name: "Portugal", continent: "europe", mapId: "620" },
  { id: "ROU", name: "Romania", continent: "europe", mapId: "642" },
  { id: "RUS", name: "Russia", continent: "europe", mapId: "643", aliases: ["Russian Federation"] },
  { id: "SMR", name: "San Marino", continent: "europe", mapId: "674", fallbackPoint: [12.46, 43.94] },
  { id: "SRB", name: "Serbia", continent: "europe", mapId: "688" },
  { id: "SVK", name: "Slovakia", continent: "europe", mapId: "703", aliases: ["Slovak Republic"] },
  { id: "SVN", name: "Slovenia", continent: "europe", mapId: "705" },
  { id: "ESP", name: "Spain", continent: "europe", mapId: "724" },
  { id: "SWE", name: "Sweden", continent: "europe", mapId: "752" },
  { id: "CHE", name: "Switzerland", continent: "europe", mapId: "756" },
  { id: "UKR", name: "Ukraine", continent: "europe", mapId: "804" },
  { id: "GBR", name: "United Kingdom", continent: "europe", mapId: "826", aliases: ["UK", "Britain", "Great Britain"] },
  { id: "VAT", name: "Vatican City", continent: "europe", mapId: "336", fallbackPoint: [12.45, 41.9], aliases: ["Vatican"] },

  { id: "AFG", name: "Afghanistan", continent: "asia", mapId: "004" },
  { id: "ARM", name: "Armenia", continent: "asia", mapId: "051" },
  { id: "AZE", name: "Azerbaijan", continent: "asia", mapId: "031" },
  { id: "BHR", name: "Bahrain", continent: "asia", mapId: "048", fallbackPoint: [50.56, 26.07] },
  { id: "BGD", name: "Bangladesh", continent: "asia", mapId: "050" },
  { id: "BTN", name: "Bhutan", continent: "asia", mapId: "064" },
  { id: "BRN", name: "Brunei", continent: "asia", mapId: "096", aliases: ["Brunei Darussalam"] },
  { id: "KHM", name: "Cambodia", continent: "asia", mapId: "116" },
  { id: "CHN", name: "China", continent: "asia", mapId: "156", aliases: ["People's Republic of China", "PRC"] },
  { id: "CYP", name: "Cyprus", continent: "asia", mapId: "196" },
  { id: "TLS", name: "East Timor", continent: "asia", mapId: "626", aliases: ["Timor-Leste"] },
  { id: "GEO", name: "Georgia", continent: "asia", mapId: "268" },
  { id: "IND", name: "India", continent: "asia", mapId: "356" },
  { id: "IDN", name: "Indonesia", continent: "asia", mapId: "360" },
  { id: "IRN", name: "Iran", continent: "asia", mapId: "364", aliases: ["Islamic Republic of Iran"] },
  { id: "IRQ", name: "Iraq", continent: "asia", mapId: "368" },
  { id: "ISR", name: "Israel", continent: "asia", mapId: "376" },
  { id: "JPN", name: "Japan", continent: "asia", mapId: "392" },
  { id: "JOR", name: "Jordan", continent: "asia", mapId: "400" },
  { id: "KAZ", name: "Kazakhstan", continent: "asia", mapId: "398" },
  { id: "KWT", name: "Kuwait", continent: "asia", mapId: "414" },
  { id: "KGZ", name: "Kyrgyzstan", continent: "asia", mapId: "417" },
  { id: "LAO", name: "Laos", continent: "asia", mapId: "418", aliases: ["Lao PDR", "Lao People's Democratic Republic"] },
  { id: "LBN", name: "Lebanon", continent: "asia", mapId: "422" },
  { id: "MYS", name: "Malaysia", continent: "asia", mapId: "458" },
  { id: "MDV", name: "Maldives", continent: "asia", mapId: "462", fallbackPoint: [73.22, 3.2] },
  { id: "MNG", name: "Mongolia", continent: "asia", mapId: "496" },
  { id: "MMR", name: "Myanmar", continent: "asia", mapId: "104", aliases: ["Burma"] },
  { id: "NPL", name: "Nepal", continent: "asia", mapId: "524" },
  { id: "PRK", name: "North Korea", continent: "asia", mapId: "408", aliases: ["DPRK", "Democratic People's Republic of Korea"] },
  { id: "OMN", name: "Oman", continent: "asia", mapId: "512" },
  { id: "PAK", name: "Pakistan", continent: "asia", mapId: "586" },
  { id: "PHL", name: "Philippines", continent: "asia", mapId: "608" },
  { id: "QAT", name: "Qatar", continent: "asia", mapId: "634", fallbackPoint: [51.18, 25.35] },
  { id: "SAU", name: "Saudi Arabia", continent: "asia", mapId: "682" },
  { id: "SGP", name: "Singapore", continent: "asia", mapId: "702", fallbackPoint: [103.82, 1.35] },
  { id: "KOR", name: "South Korea", continent: "asia", mapId: "410", aliases: ["Korea", "Republic of Korea", "ROK"] },
  { id: "LKA", name: "Sri Lanka", continent: "asia", mapId: "144" },
  { id: "SYR", name: "Syria", continent: "asia", mapId: "760", aliases: ["Syrian Arab Republic"] },
  { id: "TWN", name: "Taiwan", continent: "asia", mapId: "158", aliases: ["Republic of China"] },
  { id: "TJK", name: "Tajikistan", continent: "asia", mapId: "762" },
  { id: "THA", name: "Thailand", continent: "asia", mapId: "764" },
  { id: "TUR", name: "Turkey", continent: "asia", mapId: "792", aliases: ["Türkiye", "Turkiye"] },
  { id: "TKM", name: "Turkmenistan", continent: "asia", mapId: "795" },
  { id: "ARE", name: "United Arab Emirates", continent: "asia", mapId: "784", aliases: ["UAE", "Emirates"] },
  { id: "UZB", name: "Uzbekistan", continent: "asia", mapId: "860" },
  { id: "VNM", name: "Vietnam", continent: "asia", mapId: "704", aliases: ["Viet Nam"] },
  { id: "YEM", name: "Yemen", continent: "asia", mapId: "887" },

  { id: "DZA", name: "Algeria", continent: "africa", mapId: "012" },
  { id: "AGO", name: "Angola", continent: "africa", mapId: "024" },
  { id: "BEN", name: "Benin", continent: "africa", mapId: "204" },
  { id: "BWA", name: "Botswana", continent: "africa", mapId: "072" },
  { id: "BFA", name: "Burkina Faso", continent: "africa", mapId: "854" },
  { id: "BDI", name: "Burundi", continent: "africa", mapId: "108" },
  { id: "CMR", name: "Cameroon", continent: "africa", mapId: "120" },
  { id: "CPV", name: "Cape Verde", continent: "africa", mapId: "132", fallbackPoint: [-23.6, 15.1], aliases: ["Cabo Verde"] },
  { id: "CAF", name: "Central African Republic", continent: "africa", mapId: "140", aliases: ["CAR"] },
  { id: "TCD", name: "Chad", continent: "africa", mapId: "148" },
  { id: "COM", name: "Comoros", continent: "africa", mapId: "174", fallbackPoint: [43.3, -11.7] },
  { id: "COD", name: "Democratic Republic of the Congo", continent: "africa", mapId: "180", aliases: ["DR Congo", "DRC", "Congo-Kinshasa"] },
  { id: "DJI", name: "Djibouti", continent: "africa", mapId: "262" },
  { id: "EGY", name: "Egypt", continent: "africa", mapId: "818" },
  { id: "GNQ", name: "Equatorial Guinea", continent: "africa", mapId: "226" },
  { id: "ERI", name: "Eritrea", continent: "africa", mapId: "232" },
  { id: "SWZ", name: "Eswatini", continent: "africa", mapId: "748", aliases: ["Swaziland"] },
  { id: "ETH", name: "Ethiopia", continent: "africa", mapId: "231" },
  { id: "GAB", name: "Gabon", continent: "africa", mapId: "266" },
  { id: "GMB", name: "Gambia", continent: "africa", mapId: "270", aliases: ["The Gambia"] },
  { id: "GHA", name: "Ghana", continent: "africa", mapId: "288" },
  { id: "GIN", name: "Guinea", continent: "africa", mapId: "324" },
  { id: "GNB", name: "Guinea-Bissau", continent: "africa", mapId: "624" },
  { id: "CIV", name: "Ivory Coast", continent: "africa", mapId: "384", aliases: ["Côte d’Ivoire", "Cote d'Ivoire", "Côte d'Ivoire"] },
  { id: "KEN", name: "Kenya", continent: "africa", mapId: "404" },
  { id: "LSO", name: "Lesotho", continent: "africa", mapId: "426" },
  { id: "LBR", name: "Liberia", continent: "africa", mapId: "430" },
  { id: "LBY", name: "Libya", continent: "africa", mapId: "434" },
  { id: "MDG", name: "Madagascar", continent: "africa", mapId: "450" },
  { id: "MWI", name: "Malawi", continent: "africa", mapId: "454" },
  { id: "MLI", name: "Mali", continent: "africa", mapId: "466" },
  { id: "MRT", name: "Mauritania", continent: "africa", mapId: "478" },
  { id: "MUS", name: "Mauritius", continent: "africa", mapId: "480", fallbackPoint: [57.55, -20.2] },
  { id: "MAR", name: "Morocco", continent: "africa", mapId: "504" },
  { id: "MOZ", name: "Mozambique", continent: "africa", mapId: "508" },
  { id: "NAM", name: "Namibia", continent: "africa", mapId: "516" },
  { id: "NER", name: "Niger", continent: "africa", mapId: "562" },
  { id: "NGA", name: "Nigeria", continent: "africa", mapId: "566" },
  { id: "COG", name: "Republic of the Congo", continent: "africa", mapId: "178", aliases: ["Congo-Brazzaville"] },
  { id: "RWA", name: "Rwanda", continent: "africa", mapId: "646" },
  { id: "STP", name: "São Tomé and Príncipe", continent: "africa", mapId: "678", fallbackPoint: [6.73, 0.33], aliases: ["Sao Tome and Principe", "Sao Tome"] },
  { id: "SEN", name: "Senegal", continent: "africa", mapId: "686" },
  { id: "SYC", name: "Seychelles", continent: "africa", mapId: "690", fallbackPoint: [55.45, -4.62] },
  { id: "SLE", name: "Sierra Leone", continent: "africa", mapId: "694" },
  { id: "SOM", name: "Somalia", continent: "africa", mapId: "706" },
  { id: "ZAF", name: "South Africa", continent: "africa", mapId: "710" },
  { id: "SSD", name: "South Sudan", continent: "africa", mapId: "728" },
  { id: "SDN", name: "Sudan", continent: "africa", mapId: "729" },
  { id: "TZA", name: "Tanzania", continent: "africa", mapId: "834", aliases: ["United Republic of Tanzania"] },
  { id: "TGO", name: "Togo", continent: "africa", mapId: "768" },
  { id: "TUN", name: "Tunisia", continent: "africa", mapId: "788" },
  { id: "UGA", name: "Uganda", continent: "africa", mapId: "800" },
  { id: "ZMB", name: "Zambia", continent: "africa", mapId: "894" },
  { id: "ZWE", name: "Zimbabwe", continent: "africa", mapId: "716" },

  { id: "ATG", name: "Antigua and Barbuda", continent: "northAmerica", mapId: "028", fallbackPoint: [-61.8, 17.08] },
  { id: "BHS", name: "Bahamas", continent: "northAmerica", mapId: "044", fallbackPoint: [-77.4, 25.03], aliases: ["The Bahamas"] },
  { id: "BRB", name: "Barbados", continent: "northAmerica", mapId: "052", fallbackPoint: [-59.54, 13.19] },
  { id: "BLZ", name: "Belize", continent: "northAmerica", mapId: "084" },
  { id: "CAN", name: "Canada", continent: "northAmerica", mapId: "124" },
  { id: "CRI", name: "Costa Rica", continent: "northAmerica", mapId: "188" },
  { id: "CUB", name: "Cuba", continent: "northAmerica", mapId: "192" },
  { id: "DMA", name: "Dominica", continent: "northAmerica", mapId: "212", fallbackPoint: [-61.37, 15.41] },
  { id: "DOM", name: "Dominican Republic", continent: "northAmerica", mapId: "214" },
  { id: "SLV", name: "El Salvador", continent: "northAmerica", mapId: "222" },
  { id: "GRD", name: "Grenada", continent: "northAmerica", mapId: "308", fallbackPoint: [-61.68, 12.12] },
  { id: "GTM", name: "Guatemala", continent: "northAmerica", mapId: "320" },
  { id: "HTI", name: "Haiti", continent: "northAmerica", mapId: "332" },
  { id: "HND", name: "Honduras", continent: "northAmerica", mapId: "340" },
  { id: "JAM", name: "Jamaica", continent: "northAmerica", mapId: "388" },
  { id: "MEX", name: "Mexico", continent: "northAmerica", mapId: "484" },
  { id: "NIC", name: "Nicaragua", continent: "northAmerica", mapId: "558" },
  { id: "PAN", name: "Panama", continent: "northAmerica", mapId: "591" },
  { id: "KNA", name: "Saint Kitts and Nevis", continent: "northAmerica", mapId: "659", fallbackPoint: [-62.78, 17.36] },
  { id: "LCA", name: "Saint Lucia", continent: "northAmerica", mapId: "662", fallbackPoint: [-60.98, 13.91] },
  { id: "VCT", name: "Saint Vincent and the Grenadines", continent: "northAmerica", mapId: "670", fallbackPoint: [-61.2, 13.25] },
  { id: "TTO", name: "Trinidad and Tobago", continent: "northAmerica", mapId: "780", fallbackPoint: [-61.22, 10.69] },
  { id: "USA", name: "United States", continent: "northAmerica", mapId: "840", aliases: ["USA", "US", "United States of America", "America"] },

  { id: "ARG", name: "Argentina", continent: "southAmerica", mapId: "032" },
  { id: "BOL", name: "Bolivia", continent: "southAmerica", mapId: "068", aliases: ["Plurinational State of Bolivia"] },
  { id: "BRA", name: "Brazil", continent: "southAmerica", mapId: "076" },
  { id: "CHL", name: "Chile", continent: "southAmerica", mapId: "152" },
  { id: "COL", name: "Colombia", continent: "southAmerica", mapId: "170" },
  { id: "ECU", name: "Ecuador", continent: "southAmerica", mapId: "218" },
  { id: "GUY", name: "Guyana", continent: "southAmerica", mapId: "328" },
  { id: "PRY", name: "Paraguay", continent: "southAmerica", mapId: "600" },
  { id: "PER", name: "Peru", continent: "southAmerica", mapId: "604" },
  { id: "SUR", name: "Suriname", continent: "southAmerica", mapId: "740" },
  { id: "URY", name: "Uruguay", continent: "southAmerica", mapId: "858" },
  { id: "VEN", name: "Venezuela", continent: "southAmerica", mapId: "862", aliases: ["Bolivarian Republic of Venezuela"] },

  { id: "AUS", name: "Australia", continent: "oceania", mapId: "036" },
  { id: "FSM", name: "Federated States of Micronesia", continent: "oceania", mapId: "583", fallbackPoint: [158.2, 6.9], aliases: ["Micronesia"] },
  { id: "FJI", name: "Fiji", continent: "oceania", mapId: "242" },
  { id: "KIR", name: "Kiribati", continent: "oceania", mapId: "296", fallbackPoint: [173.0, 1.87] },
  { id: "MHL", name: "Marshall Islands", continent: "oceania", mapId: "584", fallbackPoint: [171.2, 7.1] },
  { id: "NRU", name: "Nauru", continent: "oceania", mapId: "520", fallbackPoint: [166.93, -0.52] },
  { id: "NZL", name: "New Zealand", continent: "oceania", mapId: "554" },
  { id: "PLW", name: "Palau", continent: "oceania", mapId: "585", fallbackPoint: [134.58, 7.5] },
  { id: "PNG", name: "Papua New Guinea", continent: "oceania", mapId: "598" },
  { id: "WSM", name: "Samoa", continent: "oceania", mapId: "882", fallbackPoint: [-172.1, -13.76] },
  { id: "SLB", name: "Solomon Islands", continent: "oceania", mapId: "090" },
  { id: "TON", name: "Tonga", continent: "oceania", mapId: "776", fallbackPoint: [-175.2, -21.18] },
  { id: "TUV", name: "Tuvalu", continent: "oceania", mapId: "798", fallbackPoint: [179.2, -8.52] },
  { id: "VUT", name: "Vanuatu", continent: "oceania", mapId: "548" }
];
